# Generated by Django 6.0.3 on 2026-03-09 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Extraction'), ('READY', 'Ready to Export')], default='DRAFT', max_length=20)),
                ('tax_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('document_type', models.CharField(choices=[('SALARY', 'Salary Certificate'), ('BANK', 'Bank Statement'), ('OTHER', 'Other Document')], max_length=20)),
                ('extracted_data', models.JSONField(blank=True, default=dict, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='declarations.declaration')),
            ],
        ),
    ]
